// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: idl/cart.proto

package cart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_idl_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_idl_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Item          *CartItem              `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemReq) Reset() {
	*x = AddItemReq{}
	mi := &file_idl_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemReq) ProtoMessage() {}

func (x *AddItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemReq.ProtoReflect.Descriptor instead.
func (*AddItemReq) Descriptor() ([]byte, []int) {
	return file_idl_cart_proto_rawDescGZIP(), []int{1}
}

func (x *AddItemReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddItemReq) GetItem() *CartItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResp) Reset() {
	*x = AddItemResp{}
	mi := &file_idl_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResp) ProtoMessage() {}

func (x *AddItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResp.ProtoReflect.Descriptor instead.
func (*AddItemResp) Descriptor() ([]byte, []int) {
	return file_idl_cart_proto_rawDescGZIP(), []int{2}
}

type EmptyCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyCartReq) Reset() {
	*x = EmptyCartReq{}
	mi := &file_idl_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyCartReq) ProtoMessage() {}

func (x *EmptyCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyCartReq.ProtoReflect.Descriptor instead.
func (*EmptyCartReq) Descriptor() ([]byte, []int) {
	return file_idl_cart_proto_rawDescGZIP(), []int{3}
}

func (x *EmptyCartReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemReq) Reset() {
	*x = DeleteItemReq{}
	mi := &file_idl_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemReq) ProtoMessage() {}

func (x *DeleteItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemReq.ProtoReflect.Descriptor instead.
func (*DeleteItemReq) Descriptor() ([]byte, []int) {
	return file_idl_cart_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteItemReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteItemReq) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResp) Reset() {
	*x = DeleteItemResp{}
	mi := &file_idl_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResp) ProtoMessage() {}

func (x *DeleteItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResp.ProtoReflect.Descriptor instead.
func (*DeleteItemResp) Descriptor() ([]byte, []int) {
	return file_idl_cart_proto_rawDescGZIP(), []int{5}
}

type GetCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartReq) Reset() {
	*x = GetCartReq{}
	mi := &file_idl_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartReq) ProtoMessage() {}

func (x *GetCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartReq.ProtoReflect.Descriptor instead.
func (*GetCartReq) Descriptor() ([]byte, []int) {
	return file_idl_cart_proto_rawDescGZIP(), []int{6}
}

func (x *GetCartReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResp) Reset() {
	*x = GetCartResp{}
	mi := &file_idl_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResp) ProtoMessage() {}

func (x *GetCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResp.ProtoReflect.Descriptor instead.
func (*GetCartResp) Descriptor() ([]byte, []int) {
	return file_idl_cart_proto_rawDescGZIP(), []int{7}
}

func (x *GetCartResp) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_idl_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_idl_cart_proto_rawDescGZIP(), []int{8}
}

func (x *Cart) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Cart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type EmptyCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyCartResp) Reset() {
	*x = EmptyCartResp{}
	mi := &file_idl_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyCartResp) ProtoMessage() {}

func (x *EmptyCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyCartResp.ProtoReflect.Descriptor instead.
func (*EmptyCartResp) Descriptor() ([]byte, []int) {
	return file_idl_cart_proto_rawDescGZIP(), []int{9}
}

var File_idl_cart_proto protoreflect.FileDescriptor

const file_idl_cart_proto_rawDesc = "" +
	"\n" +
	"\x0eidl/cart.proto\x12\x04cart\"E\n" +
	"\bCartItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"I\n" +
	"\n" +
	"AddItemReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\"\n" +
	"\x04item\x18\x02 \x01(\v2\x0e.cart.CartItemR\x04item\"\r\n" +
	"\vAddItemResp\"'\n" +
	"\fEmptyCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"G\n" +
	"\rDeleteItemReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\"\x10\n" +
	"\x0eDeleteItemResp\"%\n" +
	"\n" +
	"GetCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"-\n" +
	"\vGetCartResp\x12\x1e\n" +
	"\x04cart\x18\x01 \x01(\v2\n" +
	".cart.CartR\x04cart\"E\n" +
	"\x04Cart\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12$\n" +
	"\x05items\x18\x02 \x03(\v2\x0e.cart.CartItemR\x05items\"\x0f\n" +
	"\rEmptyCartResp2\xe4\x01\n" +
	"\vCartService\x120\n" +
	"\aAddItem\x12\x10.cart.AddItemReq\x1a\x11.cart.AddItemResp\"\x00\x120\n" +
	"\aGetCart\x12\x10.cart.GetCartReq\x1a\x11.cart.GetCartResp\"\x00\x126\n" +
	"\tEmptyCart\x12\x12.cart.EmptyCartReq\x1a\x13.cart.EmptyCartResp\"\x00\x129\n" +
	"\n" +
	"DeleteItem\x12\x13.cart.DeleteItemReq\x1a\x14.cart.DeleteItemResp\"\x00B\aZ\x05/cartb\x06proto3"

var (
	file_idl_cart_proto_rawDescOnce sync.Once
	file_idl_cart_proto_rawDescData []byte
)

func file_idl_cart_proto_rawDescGZIP() []byte {
	file_idl_cart_proto_rawDescOnce.Do(func() {
		file_idl_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_cart_proto_rawDesc), len(file_idl_cart_proto_rawDesc)))
	})
	return file_idl_cart_proto_rawDescData
}

var file_idl_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_idl_cart_proto_goTypes = []any{
	(*CartItem)(nil),       // 0: cart.CartItem
	(*AddItemReq)(nil),     // 1: cart.AddItemReq
	(*AddItemResp)(nil),    // 2: cart.AddItemResp
	(*EmptyCartReq)(nil),   // 3: cart.EmptyCartReq
	(*DeleteItemReq)(nil),  // 4: cart.DeleteItemReq
	(*DeleteItemResp)(nil), // 5: cart.DeleteItemResp
	(*GetCartReq)(nil),     // 6: cart.GetCartReq
	(*GetCartResp)(nil),    // 7: cart.GetCartResp
	(*Cart)(nil),           // 8: cart.Cart
	(*EmptyCartResp)(nil),  // 9: cart.EmptyCartResp
}
var file_idl_cart_proto_depIdxs = []int32{
	0, // 0: cart.AddItemReq.item:type_name -> cart.CartItem
	8, // 1: cart.GetCartResp.cart:type_name -> cart.Cart
	0, // 2: cart.Cart.items:type_name -> cart.CartItem
	1, // 3: cart.CartService.AddItem:input_type -> cart.AddItemReq
	6, // 4: cart.CartService.GetCart:input_type -> cart.GetCartReq
	3, // 5: cart.CartService.EmptyCart:input_type -> cart.EmptyCartReq
	4, // 6: cart.CartService.DeleteItem:input_type -> cart.DeleteItemReq
	2, // 7: cart.CartService.AddItem:output_type -> cart.AddItemResp
	7, // 8: cart.CartService.GetCart:output_type -> cart.GetCartResp
	9, // 9: cart.CartService.EmptyCart:output_type -> cart.EmptyCartResp
	5, // 10: cart.CartService.DeleteItem:output_type -> cart.DeleteItemResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_idl_cart_proto_init() }
func file_idl_cart_proto_init() {
	if File_idl_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_cart_proto_rawDesc), len(file_idl_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_cart_proto_goTypes,
		DependencyIndexes: file_idl_cart_proto_depIdxs,
		MessageInfos:      file_idl_cart_proto_msgTypes,
	}.Build()
	File_idl_cart_proto = out.File
	file_idl_cart_proto_goTypes = nil
	file_idl_cart_proto_depIdxs = nil
}
