run:
  timeout: 10m

issues:
  exclude-rules:
    - path: open-payment-platform/internal/payment/infrastructure/ent
      linters:
        - all
    - path: third_party$
      linters:
        - all
    - path: builtin$
      linters:
        - all
    - path: examples$
      linters:
        - all
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - staticcheck
      text: "SA1000:"
    - linters:
        - staticcheck
      text: "SA6002:"

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - unused
