// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProductsReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	CategoryName   string                 `protobuf:"bytes,3,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	DiscountFilter int32                  `protobuf:"varint,4,opt,name=discount_filter,json=discountFilter,proto3" json:"discount_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListProductsReq) Reset() {
	*x = ListProductsReq{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReq) ProtoMessage() {}

func (x *ListProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReq.ProtoReflect.Descriptor instead.
func (*ListProductsReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *ListProductsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ListProductsReq) GetDiscountFilter() int32 {
	if x != nil {
		return x.DiscountFilter
	}
	return 0
}

type Product struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Picture           string                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	Price             float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Categories        []string               `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	Sales             uint32                 `protobuf:"varint,7,opt,name=sales,proto3" json:"sales,omitempty"`
	Stock             int64                  `protobuf:"varint,8,opt,name=stock,proto3" json:"stock,omitempty"`
	DiscountType      int32                  `protobuf:"varint,9,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountValue     float32                `protobuf:"fixed32,10,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	DiscountStartTime int64                  `protobuf:"varint,11,opt,name=discount_start_time,json=discountStartTime,proto3" json:"discount_start_time,omitempty"`
	DiscountEndTime   int64                  `protobuf:"varint,12,opt,name=discount_end_time,json=discountEndTime,proto3" json:"discount_end_time,omitempty"`
	OriginalPrice     float32                `protobuf:"fixed32,13,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	ActualPrice       float32                `protobuf:"fixed32,14,opt,name=actual_price,json=actualPrice,proto3" json:"actual_price,omitempty"`
	DiscountLabel     string                 `protobuf:"bytes,15,opt,name=discount_label,json=discountLabel,proto3" json:"discount_label,omitempty"`
	DiscountStatus    int32                  `protobuf:"varint,16,opt,name=discount_status,json=discountStatus,proto3" json:"discount_status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *Product) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Product) GetSales() uint32 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *Product) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetDiscountType() int32 {
	if x != nil {
		return x.DiscountType
	}
	return 0
}

func (x *Product) GetDiscountValue() float32 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *Product) GetDiscountStartTime() int64 {
	if x != nil {
		return x.DiscountStartTime
	}
	return 0
}

func (x *Product) GetDiscountEndTime() int64 {
	if x != nil {
		return x.DiscountEndTime
	}
	return 0
}

func (x *Product) GetOriginalPrice() float32 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *Product) GetActualPrice() float32 {
	if x != nil {
		return x.ActualPrice
	}
	return 0
}

func (x *Product) GetDiscountLabel() string {
	if x != nil {
		return x.DiscountLabel
	}
	return ""
}

func (x *Product) GetDiscountStatus() int32 {
	if x != nil {
		return x.DiscountStatus
	}
	return 0
}

type ListProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResp) Reset() {
	*x = ListProductsResp{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResp) ProtoMessage() {}

func (x *ListProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResp.ProtoReflect.Descriptor instead.
func (*ListProductsResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductsResp) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReq) Reset() {
	*x = GetProductReq{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReq) ProtoMessage() {}

func (x *GetProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReq.ProtoReflect.Descriptor instead.
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResp) Reset() {
	*x = GetProductResp{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResp) ProtoMessage() {}

func (x *GetProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResp.ProtoReflect.Descriptor instead.
func (*GetProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductResp) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type SearchProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsReq) Reset() {
	*x = SearchProductsReq{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsReq) ProtoMessage() {}

func (x *SearchProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsReq.ProtoReflect.Descriptor instead.
func (*SearchProductsReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *SearchProductsReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Product             `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsResp) Reset() {
	*x = SearchProductsResp{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsResp) ProtoMessage() {}

func (x *SearchProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsResp.ProtoReflect.Descriptor instead.
func (*SearchProductsResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *SearchProductsResp) GetResults() []*Product {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Picture       string                 `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Categories    []string               `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	Stock         int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReq) Reset() {
	*x = CreateProductReq{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReq) ProtoMessage() {}

func (x *CreateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReq.ProtoReflect.Descriptor instead.
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductReq) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *CreateProductReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductReq) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *CreateProductReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type CreateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResp) Reset() {
	*x = CreateProductResp{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResp) ProtoMessage() {}

func (x *CreateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResp.ProtoReflect.Descriptor instead.
func (*CreateProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

func (x *CreateProductResp) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type UpdateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Picture       string                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Categories    []string               `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	Stock         int64                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReq) Reset() {
	*x = UpdateProductReq{}
	mi := &file_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReq) ProtoMessage() {}

func (x *UpdateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReq.ProtoReflect.Descriptor instead.
func (*UpdateProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProductReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductReq) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *UpdateProductReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductReq) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *UpdateProductReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type UpdateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResp) Reset() {
	*x = UpdateProductResp{}
	mi := &file_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResp) ProtoMessage() {}

func (x *UpdateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResp.ProtoReflect.Descriptor instead.
func (*UpdateProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProductResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IncrementSalesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementSalesReq) Reset() {
	*x = IncrementSalesReq{}
	mi := &file_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementSalesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementSalesReq) ProtoMessage() {}

func (x *IncrementSalesReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementSalesReq.ProtoReflect.Descriptor instead.
func (*IncrementSalesReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{11}
}

func (x *IncrementSalesReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IncrementSalesReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type IncrementSalesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementSalesResp) Reset() {
	*x = IncrementSalesResp{}
	mi := &file_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementSalesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementSalesResp) ProtoMessage() {}

func (x *IncrementSalesResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementSalesResp.ProtoReflect.Descriptor instead.
func (*IncrementSalesResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{12}
}

func (x *IncrementSalesResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeductStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockReq) Reset() {
	*x = DeductStockReq{}
	mi := &file_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockReq) ProtoMessage() {}

func (x *DeductStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockReq.ProtoReflect.Descriptor instead.
func (*DeductStockReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{13}
}

func (x *DeductStockReq) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeductStockReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DeductStockResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RemainingStock int64                  `protobuf:"varint,2,opt,name=remaining_stock,json=remainingStock,proto3" json:"remaining_stock,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeductStockResp) Reset() {
	*x = DeductStockResp{}
	mi := &file_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockResp) ProtoMessage() {}

func (x *DeductStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockResp.ProtoReflect.Descriptor instead.
func (*DeductStockResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{14}
}

func (x *DeductStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeductStockResp) GetRemainingStock() int64 {
	if x != nil {
		return x.RemainingStock
	}
	return 0
}

func (x *DeductStockResp) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RestoreStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreStockReq) Reset() {
	*x = RestoreStockReq{}
	mi := &file_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreStockReq) ProtoMessage() {}

func (x *RestoreStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreStockReq.ProtoReflect.Descriptor instead.
func (*RestoreStockReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{15}
}

func (x *RestoreStockReq) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *RestoreStockReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RestoreStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreStockResp) Reset() {
	*x = RestoreStockResp{}
	mi := &file_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreStockResp) ProtoMessage() {}

func (x *RestoreStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreStockResp.ProtoReflect.Descriptor instead.
func (*RestoreStockResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{16}
}

func (x *RestoreStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockReq) Reset() {
	*x = GetStockReq{}
	mi := &file_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockReq) ProtoMessage() {}

func (x *GetStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockReq.ProtoReflect.Descriptor instead.
func (*GetStockReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{17}
}

func (x *GetStockReq) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         int64                  `protobuf:"varint,1,opt,name=stock,proto3" json:"stock,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResp) Reset() {
	*x = GetStockResp{}
	mi := &file_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResp) ProtoMessage() {}

func (x *GetStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResp.ProtoReflect.Descriptor instead.
func (*GetStockResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{18}
}

func (x *GetStockResp) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GetStockResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type SetDiscountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	DiscountType  int32                  `protobuf:"varint,2,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountValue float32                `protobuf:"fixed32,3,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDiscountReq) Reset() {
	*x = SetDiscountReq{}
	mi := &file_product_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDiscountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDiscountReq) ProtoMessage() {}

func (x *SetDiscountReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDiscountReq.ProtoReflect.Descriptor instead.
func (*SetDiscountReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{19}
}

func (x *SetDiscountReq) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SetDiscountReq) GetDiscountType() int32 {
	if x != nil {
		return x.DiscountType
	}
	return 0
}

func (x *SetDiscountReq) GetDiscountValue() float32 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *SetDiscountReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SetDiscountReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type SetDiscountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDiscountResp) Reset() {
	*x = SetDiscountResp{}
	mi := &file_product_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDiscountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDiscountResp) ProtoMessage() {}

func (x *SetDiscountResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDiscountResp.ProtoReflect.Descriptor instead.
func (*SetDiscountResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{20}
}

func (x *SetDiscountResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDiscountResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelDiscountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelDiscountReq) Reset() {
	*x = CancelDiscountReq{}
	mi := &file_product_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDiscountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDiscountReq) ProtoMessage() {}

func (x *CancelDiscountReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDiscountReq.ProtoReflect.Descriptor instead.
func (*CancelDiscountReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{21}
}

func (x *CancelDiscountReq) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type CancelDiscountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelDiscountResp) Reset() {
	*x = CancelDiscountResp{}
	mi := &file_product_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDiscountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDiscountResp) ProtoMessage() {}

func (x *CancelDiscountResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDiscountResp.ProtoReflect.Descriptor instead.
func (*CancelDiscountResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{22}
}

func (x *CancelDiscountResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelDiscountResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PriceHistoryItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId         uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ChangeType        int32                  `protobuf:"varint,3,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	OldPrice          float32                `protobuf:"fixed32,4,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	NewPrice          float32                `protobuf:"fixed32,5,opt,name=new_price,json=newPrice,proto3" json:"new_price,omitempty"`
	OldDiscountType   int32                  `protobuf:"varint,6,opt,name=old_discount_type,json=oldDiscountType,proto3" json:"old_discount_type,omitempty"`
	NewDiscountType   int32                  `protobuf:"varint,7,opt,name=new_discount_type,json=newDiscountType,proto3" json:"new_discount_type,omitempty"`
	OldDiscountValue  float32                `protobuf:"fixed32,8,opt,name=old_discount_value,json=oldDiscountValue,proto3" json:"old_discount_value,omitempty"`
	NewDiscountValue  float32                `protobuf:"fixed32,9,opt,name=new_discount_value,json=newDiscountValue,proto3" json:"new_discount_value,omitempty"`
	DiscountStartTime int64                  `protobuf:"varint,10,opt,name=discount_start_time,json=discountStartTime,proto3" json:"discount_start_time,omitempty"`
	DiscountEndTime   int64                  `protobuf:"varint,11,opt,name=discount_end_time,json=discountEndTime,proto3" json:"discount_end_time,omitempty"`
	OperatorName      string                 `protobuf:"bytes,12,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	Remark            string                 `protobuf:"bytes,13,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PriceHistoryItem) Reset() {
	*x = PriceHistoryItem{}
	mi := &file_product_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceHistoryItem) ProtoMessage() {}

func (x *PriceHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceHistoryItem.ProtoReflect.Descriptor instead.
func (*PriceHistoryItem) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{23}
}

func (x *PriceHistoryItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PriceHistoryItem) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *PriceHistoryItem) GetChangeType() int32 {
	if x != nil {
		return x.ChangeType
	}
	return 0
}

func (x *PriceHistoryItem) GetOldPrice() float32 {
	if x != nil {
		return x.OldPrice
	}
	return 0
}

func (x *PriceHistoryItem) GetNewPrice() float32 {
	if x != nil {
		return x.NewPrice
	}
	return 0
}

func (x *PriceHistoryItem) GetOldDiscountType() int32 {
	if x != nil {
		return x.OldDiscountType
	}
	return 0
}

func (x *PriceHistoryItem) GetNewDiscountType() int32 {
	if x != nil {
		return x.NewDiscountType
	}
	return 0
}

func (x *PriceHistoryItem) GetOldDiscountValue() float32 {
	if x != nil {
		return x.OldDiscountValue
	}
	return 0
}

func (x *PriceHistoryItem) GetNewDiscountValue() float32 {
	if x != nil {
		return x.NewDiscountValue
	}
	return 0
}

func (x *PriceHistoryItem) GetDiscountStartTime() int64 {
	if x != nil {
		return x.DiscountStartTime
	}
	return 0
}

func (x *PriceHistoryItem) GetDiscountEndTime() int64 {
	if x != nil {
		return x.DiscountEndTime
	}
	return 0
}

func (x *PriceHistoryItem) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *PriceHistoryItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *PriceHistoryItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetProductPriceHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductPriceHistoryReq) Reset() {
	*x = GetProductPriceHistoryReq{}
	mi := &file_product_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductPriceHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductPriceHistoryReq) ProtoMessage() {}

func (x *GetProductPriceHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductPriceHistoryReq.ProtoReflect.Descriptor instead.
func (*GetProductPriceHistoryReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{24}
}

func (x *GetProductPriceHistoryReq) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetProductPriceHistoryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetProductPriceHistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PriceHistoryItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductPriceHistoryResp) Reset() {
	*x = GetProductPriceHistoryResp{}
	mi := &file_product_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductPriceHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductPriceHistoryResp) ProtoMessage() {}

func (x *GetProductPriceHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductPriceHistoryResp.ProtoReflect.Descriptor instead.
func (*GetProductPriceHistoryResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{25}
}

func (x *GetProductPriceHistoryResp) GetItems() []*PriceHistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\aproduct\"\x8e\x01\n" +
	"\x0fListProductsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\"\n" +
	"\fcategoryName\x18\x03 \x01(\tR\fcategoryName\x12'\n" +
	"\x0fdiscount_filter\x18\x04 \x01(\x05R\x0ediscountFilter\"\x8d\x04\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories\x12\x14\n" +
	"\x05sales\x18\a \x01(\rR\x05sales\x12\x14\n" +
	"\x05stock\x18\b \x01(\x03R\x05stock\x12#\n" +
	"\rdiscount_type\x18\t \x01(\x05R\fdiscountType\x12%\n" +
	"\x0ediscount_value\x18\n" +
	" \x01(\x02R\rdiscountValue\x12.\n" +
	"\x13discount_start_time\x18\v \x01(\x03R\x11discountStartTime\x12*\n" +
	"\x11discount_end_time\x18\f \x01(\x03R\x0fdiscountEndTime\x12%\n" +
	"\x0eoriginal_price\x18\r \x01(\x02R\roriginalPrice\x12!\n" +
	"\factual_price\x18\x0e \x01(\x02R\vactualPrice\x12%\n" +
	"\x0ediscount_label\x18\x0f \x01(\tR\rdiscountLabel\x12'\n" +
	"\x0fdiscount_status\x18\x10 \x01(\x05R\x0ediscountStatus\"@\n" +
	"\x10ListProductsResp\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\"\x1f\n" +
	"\rGetProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"<\n" +
	"\x0eGetProductResp\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\")\n" +
	"\x11SearchProductsReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"@\n" +
	"\x12SearchProductsResp\x12*\n" +
	"\aresults\x18\x01 \x03(\v2\x10.product.ProductR\aresults\"\xae\x01\n" +
	"\x10CreateProductReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\apicture\x18\x03 \x01(\tR\apicture\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x1e\n" +
	"\n" +
	"categories\x18\x05 \x03(\tR\n" +
	"categories\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\"2\n" +
	"\x11CreateProductResp\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\"\xbe\x01\n" +
	"\x10UpdateProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories\x12\x14\n" +
	"\x05stock\x18\a \x01(\x03R\x05stock\"-\n" +
	"\x11UpdateProductResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\x11IncrementSalesReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\".\n" +
	"\x12IncrementSalesResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x0eDeductStockReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"y\n" +
	"\x0fDeductStockResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fremaining_stock\x18\x02 \x01(\x03R\x0eremainingStock\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"L\n" +
	"\x0fRestoreStockReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\",\n" +
	"\x10RestoreStockResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\vGetStockReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\"<\n" +
	"\fGetStockResp\x12\x14\n" +
	"\x05stock\x18\x01 \x01(\x03R\x05stock\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"\xb5\x01\n" +
	"\x0eSetDiscountReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12#\n" +
	"\rdiscount_type\x18\x02 \x01(\x05R\fdiscountType\x12%\n" +
	"\x0ediscount_value\x18\x03 \x01(\x02R\rdiscountValue\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\"E\n" +
	"\x0fSetDiscountResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x11CancelDiscountReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\"H\n" +
	"\x12CancelDiscountResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x88\x04\n" +
	"\x10PriceHistoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x1f\n" +
	"\vchange_type\x18\x03 \x01(\x05R\n" +
	"changeType\x12\x1b\n" +
	"\told_price\x18\x04 \x01(\x02R\boldPrice\x12\x1b\n" +
	"\tnew_price\x18\x05 \x01(\x02R\bnewPrice\x12*\n" +
	"\x11old_discount_type\x18\x06 \x01(\x05R\x0foldDiscountType\x12*\n" +
	"\x11new_discount_type\x18\a \x01(\x05R\x0fnewDiscountType\x12,\n" +
	"\x12old_discount_value\x18\b \x01(\x02R\x10oldDiscountValue\x12,\n" +
	"\x12new_discount_value\x18\t \x01(\x02R\x10newDiscountValue\x12.\n" +
	"\x13discount_start_time\x18\n" +
	" \x01(\x03R\x11discountStartTime\x12*\n" +
	"\x11discount_end_time\x18\v \x01(\x03R\x0fdiscountEndTime\x12#\n" +
	"\roperator_name\x18\f \x01(\tR\foperatorName\x12\x16\n" +
	"\x06remark\x18\r \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03R\tcreatedAt\"P\n" +
	"\x19GetProductPriceHistoryReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"M\n" +
	"\x1aGetProductPriceHistoryResp\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.product.PriceHistoryItemR\x05items2\x89\a\n" +
	"\x15ProductCatalogService\x12E\n" +
	"\fListProducts\x12\x18.product.ListProductsReq\x1a\x19.product.ListProductsResp\"\x00\x12?\n" +
	"\n" +
	"GetProduct\x12\x16.product.GetProductReq\x1a\x17.product.GetProductResp\"\x00\x12K\n" +
	"\x0eSearchProducts\x12\x1a.product.SearchProductsReq\x1a\x1b.product.SearchProductsResp\"\x00\x12H\n" +
	"\rCreateProduct\x12\x19.product.CreateProductReq\x1a\x1a.product.CreateProductResp\"\x00\x12H\n" +
	"\rUpdateProduct\x12\x19.product.UpdateProductReq\x1a\x1a.product.UpdateProductResp\"\x00\x12K\n" +
	"\x0eIncrementSales\x12\x1a.product.IncrementSalesReq\x1a\x1b.product.IncrementSalesResp\"\x00\x12B\n" +
	"\vDeductStock\x12\x17.product.DeductStockReq\x1a\x18.product.DeductStockResp\"\x00\x12E\n" +
	"\fRestoreStock\x12\x18.product.RestoreStockReq\x1a\x19.product.RestoreStockResp\"\x00\x129\n" +
	"\bGetStock\x12\x14.product.GetStockReq\x1a\x15.product.GetStockResp\"\x00\x12B\n" +
	"\vSetDiscount\x12\x17.product.SetDiscountReq\x1a\x18.product.SetDiscountResp\"\x00\x12K\n" +
	"\x0eCancelDiscount\x12\x1a.product.CancelDiscountReq\x1a\x1b.product.CancelDiscountResp\"\x00\x12c\n" +
	"\x16GetProductPriceHistory\x12\".product.GetProductPriceHistoryReq\x1a#.product.GetProductPriceHistoryResp\"\x00B8Z6github.com/cloudwego/biz-demo/gomall/kitex_gen/productb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_product_proto_goTypes = []any{
	(*ListProductsReq)(nil),            // 0: product.ListProductsReq
	(*Product)(nil),                    // 1: product.Product
	(*ListProductsResp)(nil),           // 2: product.ListProductsResp
	(*GetProductReq)(nil),              // 3: product.GetProductReq
	(*GetProductResp)(nil),             // 4: product.GetProductResp
	(*SearchProductsReq)(nil),          // 5: product.SearchProductsReq
	(*SearchProductsResp)(nil),         // 6: product.SearchProductsResp
	(*CreateProductReq)(nil),           // 7: product.CreateProductReq
	(*CreateProductResp)(nil),          // 8: product.CreateProductResp
	(*UpdateProductReq)(nil),           // 9: product.UpdateProductReq
	(*UpdateProductResp)(nil),          // 10: product.UpdateProductResp
	(*IncrementSalesReq)(nil),          // 11: product.IncrementSalesReq
	(*IncrementSalesResp)(nil),         // 12: product.IncrementSalesResp
	(*DeductStockReq)(nil),             // 13: product.DeductStockReq
	(*DeductStockResp)(nil),            // 14: product.DeductStockResp
	(*RestoreStockReq)(nil),            // 15: product.RestoreStockReq
	(*RestoreStockResp)(nil),           // 16: product.RestoreStockResp
	(*GetStockReq)(nil),                // 17: product.GetStockReq
	(*GetStockResp)(nil),               // 18: product.GetStockResp
	(*SetDiscountReq)(nil),             // 19: product.SetDiscountReq
	(*SetDiscountResp)(nil),            // 20: product.SetDiscountResp
	(*CancelDiscountReq)(nil),          // 21: product.CancelDiscountReq
	(*CancelDiscountResp)(nil),         // 22: product.CancelDiscountResp
	(*PriceHistoryItem)(nil),           // 23: product.PriceHistoryItem
	(*GetProductPriceHistoryReq)(nil),  // 24: product.GetProductPriceHistoryReq
	(*GetProductPriceHistoryResp)(nil), // 25: product.GetProductPriceHistoryResp
}
var file_product_proto_depIdxs = []int32{
	1,  // 0: product.ListProductsResp.products:type_name -> product.Product
	1,  // 1: product.GetProductResp.product:type_name -> product.Product
	1,  // 2: product.SearchProductsResp.results:type_name -> product.Product
	23, // 3: product.GetProductPriceHistoryResp.items:type_name -> product.PriceHistoryItem
	0,  // 4: product.ProductCatalogService.ListProducts:input_type -> product.ListProductsReq
	3,  // 5: product.ProductCatalogService.GetProduct:input_type -> product.GetProductReq
	5,  // 6: product.ProductCatalogService.SearchProducts:input_type -> product.SearchProductsReq
	7,  // 7: product.ProductCatalogService.CreateProduct:input_type -> product.CreateProductReq
	9,  // 8: product.ProductCatalogService.UpdateProduct:input_type -> product.UpdateProductReq
	11, // 9: product.ProductCatalogService.IncrementSales:input_type -> product.IncrementSalesReq
	13, // 10: product.ProductCatalogService.DeductStock:input_type -> product.DeductStockReq
	15, // 11: product.ProductCatalogService.RestoreStock:input_type -> product.RestoreStockReq
	17, // 12: product.ProductCatalogService.GetStock:input_type -> product.GetStockReq
	19, // 13: product.ProductCatalogService.SetDiscount:input_type -> product.SetDiscountReq
	21, // 14: product.ProductCatalogService.CancelDiscount:input_type -> product.CancelDiscountReq
	24, // 15: product.ProductCatalogService.GetProductPriceHistory:input_type -> product.GetProductPriceHistoryReq
	2,  // 16: product.ProductCatalogService.ListProducts:output_type -> product.ListProductsResp
	4,  // 17: product.ProductCatalogService.GetProduct:output_type -> product.GetProductResp
	6,  // 18: product.ProductCatalogService.SearchProducts:output_type -> product.SearchProductsResp
	8,  // 19: product.ProductCatalogService.CreateProduct:output_type -> product.CreateProductResp
	10, // 20: product.ProductCatalogService.UpdateProduct:output_type -> product.UpdateProductResp
	12, // 21: product.ProductCatalogService.IncrementSales:output_type -> product.IncrementSalesResp
	14, // 22: product.ProductCatalogService.DeductStock:output_type -> product.DeductStockResp
	16, // 23: product.ProductCatalogService.RestoreStock:output_type -> product.RestoreStockResp
	18, // 24: product.ProductCatalogService.GetStock:output_type -> product.GetStockResp
	20, // 25: product.ProductCatalogService.SetDiscount:output_type -> product.SetDiscountResp
	22, // 26: product.ProductCatalogService.CancelDiscount:output_type -> product.CancelDiscountResp
	25, // 27: product.ProductCatalogService.GetProductPriceHistory:output_type -> product.GetProductPriceHistoryResp
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
