// Code generated by Kitex v0.16.1. DO NOT EDIT.

package product

import (
	"context"

	"github.com/cloudwego/prutal"
)

type ListProductsReq struct {
	Page         int32  `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize     int64  `protobuf:"varint,2,opt,name=pageSize" json:"pageSize,omitempty"`
	CategoryName string `protobuf:"bytes,3,opt,name=categoryName" json:"categoryName,omitempty"`
}

func (x *ListProductsReq) Reset() { *x = ListProductsReq{} }

func (x *ListProductsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListProductsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListProductsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type Product struct {
	Id          uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Picture     string   `protobuf:"bytes,4,opt,name=picture" json:"picture,omitempty"`
	Price       float32  `protobuf:"fixed32,5,opt,name=price" json:"price,omitempty"`
	Categories  []string `protobuf:"bytes,6,rep,name=categories" json:"categories,omitempty"`
	Sales       uint32   `protobuf:"varint,7,opt,name=sales" json:"sales,omitempty"`
	Stock       int64    `protobuf:"varint,8,opt,name=stock" json:"stock,omitempty"`
}

func (x *Product) Reset() { *x = Product{} }

func (x *Product) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Product) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Product) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *Product) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Product) GetSales() uint32 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *Product) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ListProductsResp struct {
	Products []*Product `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
}

func (x *ListProductsResp) Reset() { *x = ListProductsResp{} }

func (x *ListProductsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListProductsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListProductsResp) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetProductReq struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *GetProductReq) Reset() { *x = GetProductReq{} }

func (x *GetProductReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetProductReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetProductReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductResp struct {
	Product *Product `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
}

func (x *GetProductResp) Reset() { *x = GetProductResp{} }

func (x *GetProductResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetProductResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetProductResp) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type SearchProductsReq struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
}

func (x *SearchProductsReq) Reset() { *x = SearchProductsReq{} }

func (x *SearchProductsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchProductsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchProductsReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchProductsResp struct {
	Results []*Product `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (x *SearchProductsResp) Reset() { *x = SearchProductsResp{} }

func (x *SearchProductsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchProductsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchProductsResp) GetResults() []*Product {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreateProductReq struct {
	Name        string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Picture     string   `protobuf:"bytes,3,opt,name=picture" json:"picture,omitempty"`
	Price       float32  `protobuf:"fixed32,4,opt,name=price" json:"price,omitempty"`
	Categories  []string `protobuf:"bytes,5,rep,name=categories" json:"categories,omitempty"`
	Stock       int64    `protobuf:"varint,6,opt,name=stock" json:"stock,omitempty"`
}

func (x *CreateProductReq) Reset() { *x = CreateProductReq{} }

func (x *CreateProductReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateProductReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductReq) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *CreateProductReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductReq) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *CreateProductReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type CreateProductResp struct {
	ProductId uint32 `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
}

func (x *CreateProductResp) Reset() { *x = CreateProductResp{} }

func (x *CreateProductResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateProductResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateProductResp) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type UpdateProductReq struct {
	Id          uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Picture     string   `protobuf:"bytes,4,opt,name=picture" json:"picture,omitempty"`
	Price       float32  `protobuf:"fixed32,5,opt,name=price" json:"price,omitempty"`
	Categories  []string `protobuf:"bytes,6,rep,name=categories" json:"categories,omitempty"`
	Stock       int64    `protobuf:"varint,7,opt,name=stock" json:"stock,omitempty"`
}

func (x *UpdateProductReq) Reset() { *x = UpdateProductReq{} }

func (x *UpdateProductReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateProductReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateProductReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductReq) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *UpdateProductReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductReq) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *UpdateProductReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type UpdateProductResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *UpdateProductResp) Reset() { *x = UpdateProductResp{} }

func (x *UpdateProductResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateProductResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateProductResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IncrementSalesReq struct {
	Id       uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Quantity int32  `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
}

func (x *IncrementSalesReq) Reset() { *x = IncrementSalesReq{} }

func (x *IncrementSalesReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *IncrementSalesReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *IncrementSalesReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IncrementSalesReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type IncrementSalesResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *IncrementSalesResp) Reset() { *x = IncrementSalesResp{} }

func (x *IncrementSalesResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *IncrementSalesResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *IncrementSalesResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeductStockReq struct {
	ProductId uint32 `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
	Quantity  int32  `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
}

func (x *DeductStockReq) Reset() { *x = DeductStockReq{} }

func (x *DeductStockReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeductStockReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeductStockReq) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeductStockReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DeductStockResp struct {
	Success        bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	RemainingStock int64  `protobuf:"varint,2,opt,name=remaining_stock" json:"remaining_stock,omitempty"`
	ErrorMessage   string `protobuf:"bytes,3,opt,name=error_message" json:"error_message,omitempty"`
}

func (x *DeductStockResp) Reset() { *x = DeductStockResp{} }

func (x *DeductStockResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeductStockResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeductStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeductStockResp) GetRemainingStock() int64 {
	if x != nil {
		return x.RemainingStock
	}
	return 0
}

func (x *DeductStockResp) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RestoreStockReq struct {
	ProductId uint32 `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
	Quantity  int32  `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
}

func (x *RestoreStockReq) Reset() { *x = RestoreStockReq{} }

func (x *RestoreStockReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RestoreStockReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RestoreStockReq) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *RestoreStockReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RestoreStockResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *RestoreStockResp) Reset() { *x = RestoreStockResp{} }

func (x *RestoreStockResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RestoreStockResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RestoreStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetStockReq struct {
	ProductId uint32 `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
}

func (x *GetStockReq) Reset() { *x = GetStockReq{} }

func (x *GetStockReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetStockReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetStockReq) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetStockResp struct {
	Stock  int64 `protobuf:"varint,1,opt,name=stock" json:"stock,omitempty"`
	Exists bool  `protobuf:"varint,2,opt,name=exists" json:"exists,omitempty"`
}

func (x *GetStockResp) Reset() { *x = GetStockResp{} }

func (x *GetStockResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetStockResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetStockResp) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GetStockResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type ProductCatalogService interface {
	ListProducts(ctx context.Context, req *ListProductsReq) (res *ListProductsResp, err error)
	GetProduct(ctx context.Context, req *GetProductReq) (res *GetProductResp, err error)
	SearchProducts(ctx context.Context, req *SearchProductsReq) (res *SearchProductsResp, err error)
	CreateProduct(ctx context.Context, req *CreateProductReq) (res *CreateProductResp, err error)
	UpdateProduct(ctx context.Context, req *UpdateProductReq) (res *UpdateProductResp, err error)
	IncrementSales(ctx context.Context, req *IncrementSalesReq) (res *IncrementSalesResp, err error)
	DeductStock(ctx context.Context, req *DeductStockReq) (res *DeductStockResp, err error)
	RestoreStock(ctx context.Context, req *RestoreStockReq) (res *RestoreStockResp, err error)
	GetStock(ctx context.Context, req *GetStockReq) (res *GetStockResp, err error)
}
