CREATE DATABASE `checkout` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */

CREATE TABLE `local_message` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `message_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `business_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Business operation ID (e.g., order_id)',
  `message_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Message type: stock_deduct, stock_restore, order_create, payment, email',
  `target_service` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Target service name',
  `target_method` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Target method name',
  `payload` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Message payload in JSON format',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT 'pending' COMMENT 'Message status: pending, sent, confirmed, failed, cancelled',
  `retry_count` int DEFAULT '0' COMMENT 'Number of retry attempts',
  `max_retry` int DEFAULT '5' COMMENT 'Maximum retry attempts',
  `next_retry_at` datetime DEFAULT NULL COMMENT 'Next scheduled retry time',
  `last_retry_at` datetime DEFAULT NULL COMMENT 'Last retry attempt time',
  `error_message` text COLLATE utf8mb4_unicode_ci COMMENT 'Last error message',
  `confirm_at` datetime DEFAULT NULL COMMENT 'Confirmation time',
  `priority` int DEFAULT '0' COMMENT 'Message priority (higher = more important)',
  `correlation_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Correlation ID for tracing',
  `callback_url` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Callback URL for confirmation',
  `callback_status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Callback status',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_message_id` (`message_id`),
  KEY `idx_business_id` (`business_id`),
  KEY `idx_status` (`status`),
  KEY `idx_status_next_retry` (`status`,`next_retry_at`),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `idx_priority` (`priority`),
  KEY `idx_correlation_id` (`correlation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Local message table for outbox pattern'

CREATE TABLE `local_message` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `message_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `business_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Business operation ID (e.g., order_id)',
  `message_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Message type: stock_deduct, stock_restore, order_create, payment, email',
  `target_service` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Target service name',
  `target_method` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Target method name',
  `payload` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Message payload in JSON format',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT 'pending' COMMENT 'Message status: pending, sent, confirmed, failed, cancelled',
  `retry_count` int DEFAULT '0' COMMENT 'Number of retry attempts',
  `max_retry` int DEFAULT '5' COMMENT 'Maximum retry attempts',
  `next_retry_at` datetime DEFAULT NULL COMMENT 'Next scheduled retry time',
  `last_retry_at` datetime DEFAULT NULL COMMENT 'Last retry attempt time',
  `error_message` text COLLATE utf8mb4_unicode_ci COMMENT 'Last error message',
  `confirm_at` datetime DEFAULT NULL COMMENT 'Confirmation time',
  `priority` int DEFAULT '0' COMMENT 'Message priority (higher = more important)',
  `correlation_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Correlation ID for tracing',
  `callback_url` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Callback URL for confirmation',
  `callback_status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Callback status',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_message_id` (`message_id`),
  KEY `idx_business_id` (`business_id`),
  KEY `idx_status` (`status`),
  KEY `idx_status_next_retry` (`status`,`next_retry_at`),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `idx_priority` (`priority`),
  KEY `idx_correlation_id` (`correlation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Local message table for outbox pattern'

CREATE TABLE `message_retry_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `message_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Message ID',
  `retry_count` int NOT NULL COMMENT 'Retry attempt number',
  `attempt_at` datetime NOT NULL COMMENT 'Attempt timestamp',
  `success` tinyint(1) NOT NULL COMMENT 'Whether attempt succeeded',
  `error_message` text COLLATE utf8mb4_unicode_ci COMMENT 'Error message if failed',
  `duration` bigint DEFAULT '0' COMMENT 'Attempt duration in milliseconds',
  PRIMARY KEY (`id`),
  KEY `idx_message_id` (`message_id`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Message retry log for auditing'

